<?php

return array(	
	'manager_project' => 5,
	// 'manager_salary' => 18,
	'manager_permission' => 8,
	'user_delete' => 11,
	'change_password' => 7,
	'add_user_manage' => 9,
	'edit_normal' => 5,
	'edit_advandce' => 6,
	'user_edit' => 10,
	'user_view' => 12,
	'manage_salary_propose' => 22,
	'manage_salary_approve' => 23,
	// 'manager_regency' => 7,
	// 'manager_department' => 8,
	// 'manager_regency' => 24,
	// 'manager_type' => 25,
	// 'manager_user' => 26,
	// 'report_category' => 27,
	// 'notification_category' => 28,
	//cong van giay to
	'manager_archive' => 38,
	'archive_add' => 39,
	'archive_edit' => 40,
	'archive_delete' => 41,
	'archive_show' => 42,
	//hop dong
	'manager_contract' => 43,
	'contract_add' => 44,
	'contract_edit' => 45,
	'contract_delete' => 46,
	'contract_show' => 47,
	//đối tác
	'manager_partner' => 48,
	'partner_add' => 49,
	'partner_edit' => 50,
	'partner_delete' => 51,
	//Thiết bị
	'manager_office' => 52,
	'office_add' => 53,
	'office_edit' => 54,
	'office_delete' => 55,
	'office_show' => 56,
	//máy tính
	'manager_computer' => 57,
	'computer_add' => 58,
	'computer_edit' => 59,
	'computer_delete' => 60,
	'computer_show' => 61,
	//tài liệu
	'manager_document' => 62,
	'document_add' => 63,
	'document_edit' => 64,
	'document_delete' => 65,
	'document_show' => 66,
	//Tên miền
	'manager_domain' => 67,
	'domain_add' => 68,
	'domain_edit' => 69,
	'domain_delete' => 70,
	'domain_show' => 71,

);
